

GET http://localhost:3000/books

###

POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{ 
    "titulo": "Express and MongoDB",
    "editora": "Dev",
    "preco": 500,
    "paginas": 30
}

###

PUT http://localhost:3000/books/6576d6ce268e4cc67e1426db HTTP/1.1
content-type: application/json

{ 
    "editora": "Dev Modificado"
}

###

DELETE http://localhost:3000/books/6576d6ce268e4cc67e1426db HTTP/1.1
